<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="14" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-28T11:21:46 EST" name="Testing_Suite1" finished-at="2022-11-28T11:21:46 EST" duration-ms="198">
    <groups>
      <group name="Sanity">
        <method signature="Module1.test001()[pri:0, instance:testng_Suite1.Module1@16ec5519]" name="test001" class="testng_Suite1.Module1"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="Module1.test001()[pri:0, instance:testng_Suite1.Module1@16ec5519]" name="test001" class="testng_Suite1.Module1"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-11-28T11:21:46 EST" name="Module_Test" finished-at="2022-11-28T11:21:46 EST" duration-ms="198">
      <class name="testng_Suite1.Module1">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testng_Suite1.Module1@16ec5519]" started-at="2022-11-28T11:21:46 EST" name="beforeMethod" finished-at="2022-11-28T11:21:46 EST" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test001()[pri:0, instance:testng_Suite1.Module1@16ec5519]" started-at="2022-11-28T11:21:46 EST" name="test001" finished-at="2022-11-28T11:21:46 EST" duration-ms="33" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at testng_Suite1.Module1.test001(Module1.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testng_Suite1.Module1@16ec5519]" started-at="2022-11-28T11:21:46 EST" name="afterMethod" finished-at="2022-11-28T11:21:46 EST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testng_Suite1.Module1 -->
      <class name="testng_Suite1.Module2">
        <test-method signature="test001()[pri:0, instance:testng_Suite1.Module2@6aba2b86]" started-at="2022-11-28T11:21:46 EST" name="test001" finished-at="2022-11-28T11:21:46 EST" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001 -->
        <test-method signature="test002()[pri:0, instance:testng_Suite1.Module2@6aba2b86]" started-at="2022-11-28T11:21:46 EST" name="test002" finished-at="2022-11-28T11:21:46 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002 -->
      </class> <!-- testng_Suite1.Module2 -->
    </test> <!-- Module_Test -->
  </suite> <!-- Testing_Suite1 -->
  <suite started-at="2022-11-28T11:21:47 EST" name="Testing_Suite1 (0)" finished-at="2022-11-28T11:21:47 EST" duration-ms="10">
    <groups>
      <group name="Sanity">
        <method signature="Module1.test001()[pri:0, instance:testng_Suite1.Module1@35cabb2a]" name="test001" class="testng_Suite1.Module1"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="Module1.test001()[pri:0, instance:testng_Suite1.Module1@35cabb2a]" name="test001" class="testng_Suite1.Module1"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-11-28T11:21:47 EST" name="Module_Test" finished-at="2022-11-28T11:21:47 EST" duration-ms="10">
      <class name="testng_Suite1.Module1">
        <test-method signature="test001()[pri:0, instance:testng_Suite1.Module1@35cabb2a]" started-at="2022-11-28T11:21:47 EST" name="test001" finished-at="2022-11-28T11:21:47 EST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at testng_Suite1.Module1.test001(Module1.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001 -->
      </class> <!-- testng_Suite1.Module1 -->
    </test> <!-- Module_Test -->
  </suite> <!-- Testing_Suite1 (0) -->
</testng-results>
